import = ["/home/arnaup/.config/alacritty/themes/themes/tokyo-night.toml"]
# working_directory = "/home/arnaup/"

[font]
size = 15

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 2000

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 1.0
title = "Alacritty Terminal"

[window.padding]
x = 10
y = 4

# INFO from: https://github.com/chrisduerr/dotfiles/commit/9bde03067a2d1e12f4db9bed92860669c0122765
[colors.hints.start]
foreground = "#181818"
background = "#ac4242"

[colors.hints.end]
background = "#ac4242"
foreground = "#181818"

[[hints.enabled]]
regex = """(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
    [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"""
hyperlinks = true
command = "google-chrome"
post_processing = true
mouse = { enabled = true }
binding = { key = "L", mods = "Control|Shift" }

[[hints.enabled]]
regex = "[a-f0-9]{40}|[a-f0-9]{7,8}"
action = "Copy"
binding = { key = "H", mods = "Control|Shift" }

[[hints.enabled]]
regex = """(/?[^/ \"']*[a-zA-Z0-9][^/ \"':]*/([^/ \"':]+/?)*)\
    |(/[^/ \"']*[a-zA-Z0-9][^/ \"']*)"""
action = "Copy"
binding = { key = "P", mods = "Control|Shift" }

[[hints.enabled]]
regex = """(https?://[a-zA-Z0-9._/\\-:]+)"""
action = "Copy"
binding = { key = "L", mods = "Control|Shift" }

[[hints.enabled]]
regex = """\\{.+\\}"""
action = "Copy"
binding = { key = "D", mods = "Control|Shift" }


[[hints.enabled]]
regex = """\\s[\\w_]*\\("""
action = "Copy"
post_processing = true
binding = { key = "F", mods = "Control|Shift" }
