import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]
working_directory = "/home/pontsoul/"

[shell]
program = "/usr/bin/zsh"

[window]
title = "Alacritty Terminal"
opacity = 0.8
# decoration = "buttonless"
[window.padding]
y = 4
x = 10

[selection]
save_to_clipboard = true

[scrolling]
history = 2000

[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font"

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"
